spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_DATABASE:data}?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${DB_USER:thaiph}
    password: ${DB_PASSWORD:gaion00}
    properties:
      hibernate.connection.charSet: UTF-8
      hibernate.dialect: org.hibernate.dialect.MariaDBDialect
      hibernate.show_sql: true
  jpa:
    open-in-view: false

#auth:
#  secret: ${AUTH_SECRET_KEY:drone}
#  issuer: GAION
#  expiresAfter: 1000 #hours
#
#logging:
#  file:
#    name: log/application.log
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type: TRACE


